### ISSUE TITLE
Can't run template: LegacyForms is undefined

### ISSUE THREAD

**Issue by datto-aparrill** [grafana/simple-datasource#8]
I've checked out master (9670d122aa17b3cc1d9d18fd83215eb77c934793), built it with `yarn` and `yarn dev`, and scp'ed it over to the grafana v6.7.3 plugins directory. Navigating to the plugin options or trying to add a datasource using the plugin results in the following error in the console:

```
Failed to import plugin module Error: "_grafana_ui__WEBPACK_IMPORTED_MODULE_2__.LegacyForms is undefined
  Evaluating http://dlt-monitoring-grafana-1.datto.lan/public/plugins/myorgid-simple-datasource/module.js
  Loading plugins/myorgid-simple-datasource/module"
```

**Comment by Sniper91** [comment]
you must run the plugin with grafana v7.0.0

**Comment by datto-aparrill** [comment]
Isn't v7 still in beta? Is there a commit that works with a stable version?

I also have an older plugin that uses the same {{LegacyForms}} object and fails with a similar error, so its not like this was added in v7... is it?

**Comment by Sniper91** [comment]
the developing doc and demo of grafana plugin is really tricky
the demo run with v7 is ok
